language: java
jdk:
- oraclejdk8
deploy:
  provider: bintray
  file: bintray.json
  user: inkycoder
  key:
    secure: i84VBiCMDxA78ozWa2AxUN4JIqJULPFjVhFJwPF1V5fCYMjBdzr/0rUL74etk4mN2H+H8aocQ/bUyBMvHlPC9XqGgV08kd86vtB+ZAVnz9Ns9+VPLObNO0UyuCEtoQ5mMyFd9HXB2U1jAVNnrs2wBHcJSNCQ/wG37ffpYt75qexOOWXVpaRxlItnzAHHZvir7fzYNGdy1lAm1cGE91wQAuge5B6uTkNIDcYKJcYg1lXiQEGVZp1kz0zPUBemiGvV7CEutc9TwRaPGZ5hwVGH8A8oLPhYZNuVkIKgqeQDFsn4ioKrR0+ilXaOP6JAWF1XpFanKmaD5FAV1GQ+9jiLDUxY9yJP/BevhKobhzZsWjYRBcbfYBXhgCYcqmOzZG6VST3wjZAdPurc+MD+JFyuxCP8ySe9F6Xy94qdkZG6K/HzbbryvVOouHr5o512C3LhWyLy62tXQlEYgGPYz3e31cv6RBq1Ne7/F8xs7iCy0rHIdfXkV9czsF2frQq43WpFQvNhNeV4VbGqlKvlHlnJWob18Fa7phDSnyd8DVP/FdtCbiQTFkmfnnHPNVKi85UzKC8+ZTWAv1Mv5raZWBIYc7dEKx7Gm8bqGGoQv4PcxSSID0lmeUPQChmqXmNz9WsXtiMH4/XwkpeP7R3RBn8b2Y1eV4cP0MQeIILQlRq3HEY=
